### ISSUE TITLE
ExceptionsManager.js:63 Cannot read property 'checkAuthorizationStatus' of undefined

### ISSUE THREAD

**Issue by haomingden** [jsierles/react-native-audio#144] opened 2017-01-13 08:48 UTC
Module AppRegistry is not a registered callable module (calling runApplication)
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:108
reportFatalError @ error-guard.js:40
guard @ MessageQueue.js:48
callFunctionReturnFlushedQueue @ MessageQueue.js:107
onmessage @ debuggerWorker.js:44
ExceptionsManager.js:71 Unhandled JS Exception: Cannot read property 'checkAuthorizationStatus' of undefined
reactConsoleErrorHandler @ ExceptionsManager.js:71
logIfNoNativeHook @ RCTLog.js:38
__callFunction @ MessageQueue.js:236
(anonymous) @ MessageQueue.js:108
guard @ MessageQueue.js:46
callFunctionReturnFlushedQueue @ MessageQueue.js:107
onmessage @ debuggerWorker.js:44
ExceptionsManager.js:71 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by bruckmatthew** [comment] 2017-01-18 00:55
Did you link the module in the cli? -> react-native link react-native-audio

**Comment by jsierles** [comment] 2017-01-24 14:55
Not able to reproduce this myself. Closing - feel free to reopen if this issue persists.

**Closed by jsierles** 2017-01-24 14:55 UTC

**Comment by tmaly1980** [comment] 2017-08-24 22:16
The app works fine for me on iOS, so it's not an issue with react-native link, unless the android part of that script is broken.

**Comment by tmaly1980** [comment] 2017-08-24 22:43
OK I think I figured out the problem. For some reason, my MainApplication.java wasn't being updated, so I had to remove the gradle code above for it to properly re-link. Otherwise it's convinced it's done when MainApplication.java is not being touched. I noticed it added:

`import com.rnim.rn.audio.ReactNativeAudioPackage;`

and inside getPackages():
`            new ReactNativeAudioPackage(),`
