### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by mobileDevNativeCross** [jsierles/react-native-audio#88] opened 2016-09-14 05:34 UTC
Hello.
On iOS work perfect but on Android not calling this method:
`AudioRecorder.onProgress = (data) => {
        this.setState({currentTime: Math.floor(data.currentTime)});
      };`
And on Android Studio log error:
`the third app: com.appname use permission: Use microphone
MediaRecorder start mz   CallingPid =  28888  Callinguid=  10411 mPath = /data/data/com.chator/files/test.aac`

**Comment by RakanNimer** [comment] 2016-09-14 05:38
Hey @mobileDevNativeCross,
This is an expected error : onProgress has not yet been implemented on Android. 
I will see with @jsierles how to add a fix for this while I work on adding the progress logic in Java.

**Comment by jsierles** [comment] 2016-09-14 12:53
What's the cause of the second error? Maybe we should open a separate issue for it.

**Comment by RakanNimer** [comment] 2016-09-14 13:02
@mobileDevNativeCross, Did you add RECORD_AUDIO permission to android
manifest.xml ?

**Comment by RakanNimer** [comment] 2016-09-16 13:39
@mobileDevNativeCross any update there ?

**Comment by jsierles** [comment] 2016-09-17 14:29
Closing this as it seems related to permissions. Tracking Android progress reporting in #93.

**Closed by jsierles** 2016-09-17 14:29 UTC
