### ISSUE TITLE
Expose binary recording data to "progress subscribers"

### ISSUE THREAD

**Issue by superquest** [jsierles/react-native-audio#138] opened 2017-01-05 12:21 UTC
My objective to broadcast binary audio data over a websocket as it's being recorded.

It seems the data sent to "progress subscribers" contains only `currentTime`. Would it be possible to send include binary audio data, similar to the WebAudio API's [ScriptProcessorNode.onaudioprocess](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode/onaudioprocess) callback?

Maybe I'm going about this in the wrong way? Any tips or feedback would be greatly appreciated!

**Comment by superquest** [comment] 2017-01-08 10:04
For now I'm working to port [cordova-plugin-audioinput](https://github.com/edimuj/cordova-plugin-audioinput) to React Native. 

If I ever wrap my head around the native code I might try to send a pull request. No promises!

**Comment by RakanNimer** [comment] 2017-01-08 11:27
Hey superquest,

A pull request that does that would be great but keep in mind that sending large amounts of serialized data from the native to the JS thread might have a non-negligible performance cost. 

If you're working on the native side than it might be a better idea to do the streaming logic from the native thread. You would only inform the JS thread about streaming progress. 

Exposing a new method to [AudioRecorderManager](https://github.com/jsierles/react-native-audio/blob/master/android/src/main/java/com/rnim/rn/audio/AudioRecorderManager.java) or adding a property to [startRecording](https://github.com/jsierles/react-native-audio/blob/master/android/src/main/java/com/rnim/rn/audio/AudioRecorderManager.java#L150) would be the most straight forward way to do that on Android.

Cheers

**Comment by ohtangza** [comment] 2017-01-09 12:32
I also want to get byte stream in JS thread despite the non-negligible performance cost. I believe that every functionality should be supported purely with JS because this is what RN eventually heads for and audio processing is pretty doable in mobile device now (even in JS thread). Also, I believe audio byte stream is worth supported in that it became a basic component for many apps. As of 2016, lots of speech related APIs now got publicly accessible like Google Speech API and IBM Watson Speech recognitions, which supports real-time streaming. As @RakanNimer mentioned, it is better if we can selectively enable this feature as the developer needs.

By the way, the progress update is not currently available for Android mainly because MediaRecorder class, which react-native-audio relies on, does not support progress update. 

To make it realized, for Android implementation, we need to use AudioRecord class instead of MediaRecorder class, which makes inconsistency with the existing code. It would not be easy to support this feature without changing the core of this library. How about iOS side, any idea? (I can only read for RN and Android codes.)

**Comment by ohtangza** [comment] 2017-01-09 12:33
And, also, RN native codes may not support ByteArray delivered from native source code. How would it be delivered from native code to JS code. Perhaps, we need to encode it to Base64?

**Comment by jsierles** [comment] 2017-01-24 14:54
If there's interest in this, happy to see a PR. Closing for now!

**Closed by jsierles** 2017-01-24 14:54 UTC

**Comment by rohitgoyal** [comment] 2017-07-30 18:42
Is there any way i can get the recording sound in chunk to broadcast it to other clients via socket. If it is not supported can you help me how to convert the .aac file to a blob or arraybuffer?

**Comment by MrLoh** [comment] 2017-07-30 22:27
@rohitgoyal basically you can't with any library. We are having the same problem. The issue is that there is no library that supports streaming chunks of data to the JS site. And there is no library to decode the aac file, as JS in react native doesn't have the audio context (unlike node and modern browsers) that all libraries depend on. We need to decode to the wave signal, soaybe you will have more luck finding an easier solution, but audio is really crippled at the moment in Reacht native. We are. Currently looking into porting the Cordova plugin to react native, but we are no experts on this either. If you come across any other solution, let us know.

**Comment by rohitgoyal** [comment] 2017-07-31 05:26
@MrLoh According to you what is the best way currently to record a sound and broadcast to other users using socket.io on nodejs server?
I am using react-native-sound to play the sound.

**Comment by MrLoh** [comment] 2017-07-31 09:15
@rohitgoyal As long as your en/de-coding is not audio specific and doesn't need an audio context, you should be fine, I guess. You will still have to write and read files all the time though and not sure how chunking the files would work well. It's sad that react native's js engine is so lacking. 

Someone really need to port the cordova plugin though to do the relevant stuff on the native side as the js engine in react native is quite crippled when it comes to audio. And the current solution of reading and writing files is terribly unefficiant.

**Comment by rohitgoyal** [comment] 2017-07-31 13:31
@MrLoh It is not audio specific. I used react-native-fs to encode the .aac to base64 string. 
However there is not support in react-native-fs to decode that back to .aac. 
Do you know of any way to play sound using base64 or a way to decode base64 back to .aac in react native?

**Comment by MrLoh** [comment] 2017-07-31 14:30
@rohitgoyal no, sorry, I haven't worked with base64 in RN before.

**Comment by ohtangza** [comment] 2017-08-01 03:10
@rohitgoyal I think base64 is just plan string with certain encoding rule, you can refer the resources on SO, I guess.

For your information, in my app's implementation, we worked on native code to stream the binary data to JS code using WritableArray. One issue here is that in Android implementation, the transferring through base64 encoding/decoding seems to be faster than the provided WritabelArray.

**Comment by rohitgoyal** [comment] 2017-08-01 05:40
@ohtangza 
This seems weird. You tried to write the array in chunks as the recording was done? 

I have a base64 for a .wav file which while testing on some online base64 decoder gives me back the .wav file. But I am not able to get the correct .wav file from the base64 string on my react-native app. 
I am using react-native-fs encode/decode for this. I think the decode functionality is not build for sound file in case of this library. 
Which library are you using to decode/encode the base64 string?

**Comment by MrLoh** [comment] 2017-08-01 07:34
@ohtangza Could you share your code?

**Comment by ohtangza** [comment] 2017-08-02 17:03
@rohitgoyal @MrLoh You can refer the code here. We plan to make a pull request with this, but I am not sure if the author would accept it. In our application, streaming audio to JS code is pretty critical so we implemented it. Currently, this work is being done by https://github.com/ghsdh3409 who is my co-worker. Let us know if you have any idea or feedback.

**Comment by rohitgoyal** [comment] 2017-08-03 06:49
@ohtangza Which one is the code? Are you referring to react-native-audio-toolkit?

**Comment by ohtangza** [comment] 2017-08-04 02:16
@rohitgoyal Oh, sorry. I added the link above. It's still work-in-progress, but the binary streaming function should work.

**Comment by wangping0105** [comment] 2017-11-28 09:19
@ohtangza hello, how about your branch  (https://github.com/hayanmind/react-native-audio/tree/feature/streaming-recording), when would it be merged?

**Comment by niocncn** [comment] 2018-07-18 11:24
any updates on it?

**Comment by teslavitas** [comment] 2019-09-11 08:01
Is there a progress with live audio streaming on React Native? I found a react-native-audio-record library which returns base64-encoded sound online, but cannot make it work on iOS.

**Comment by AnanasPie** [comment] 2019-09-13 12:45
Hi, same problem as @teslavitas  has.
